language: go
sudo: false
go:
  - 1.13
  
before_install:
  - go get github.com/mattn/goveralls
  
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
  - $GOPATH/bin/goveralls -service=travis-ci
